### ISSUE TITLE
Make the backend Node SDK compatible with NextJS, NestJS and Remix

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#710] opened 2023-06-29 12:54 UTC
Following a conversation with a user, apparently the backend Node SDK has a compilation error with Nest that we should fix.

References 
* https://nextjs.org/docs/messages/import-esm-externals

**Comment by rguldener** [comment] 2023-07-01 09:05
We had another 2 users report issues with using the node SDK from Nango in Next JS projects.
I changed the title on this one as I think the issue may have the same root cause.

A pretty long thread on the Nango community with 2 users: https://nango-community.slack.com/archives/C04ABR352H0/p1681997458887909

The same issue has since also been reported by:
- Tyler (Tennr, not sure which framework)
- Tristan Tarpley (on the Slack community, uses nextJS)

The error people report:
```
╰─$ npx ts-node src/test.ts                                                                                                                                                                                                                    130 ↵
/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/aric/dust/dust/connectors/node_modules/@nangohq/node/dist/index.js from /Users/aric/dust/dust/connectors/src/api/connector.ts not supported.
Instead change the require of index.js in /Users/aric/dust/dust/connectors/src/api/connector.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/aric/dust/dust/connectors/src/api/connector.ts:42:14)
    at m._compile (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/aric/dust/dust/connectors/src/test.ts:39:19)
    at m._compile (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/bin.js:54:12)
    at main (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/aric/dust/dust/connectors/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by khaliqgant** [comment] 2023-07-03 20:02
- [x] Tested using latest next.js -- worked without any issues
- [x] Tested using nest.js. Saw that same error. Followed the advice https://github.com/nestjs/nest/issues/11046#issuecomment-1416983059 and it loaded
```
# tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "Node16",
...
}

# main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const { Nango } = await import('@nangohq/node');
  console.log(new Nango());
  await app.listen(3000);
}
bootstrap();
```

Gives this result
```
[Nest] 29068  - 07/03/2023, 10:59:39 PM     LOG [NestFactory] Starting Nest application...
[Nest] 29068  - 07/03/2023, 10:59:39 PM     LOG [InstanceLoader] AppModule dependencies initialized +5ms
Nango {
  serverUrl: 'https://api.nango.dev',
  secretKey: '',
  connectionId: '',
  providerConfigKey: '',
  isSync: false,
  dryRun: false,
  activityLogId: undefined
```
- [x] Remix was formerly tested and confirmed as working with https://github.com/NangoHQ/nango/pull/686#issue-1769479498 

cc/ @rguldener @bastienbeurier

**Comment by khaliqgant** [comment] 2023-07-03 20:15
Closing this as I am unsure what else can be done further, but we can reopen as new conditions/scenarios come in

**Closed as completed by khaliqgant** 2023-07-03 20:15 UTC
Labels: bug

**Comment by bastienbeurier** [comment] 2023-07-07 12:45
A customer managed to fix this by simply changing the import to: 
![image (2)](https://github.com/NangoHQ/nango/assets/2560456/d9dacc35-f344-42bd-a22e-d8b70259bc28)

There `tsconfig` had: `"module": "commonjs"` and `"moduleResolution": "node"`
