### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [NangoHQ/nango#989] opened 2023-09-10 14:36 UTC
Describe the bug
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Steps To Reproduce
Scroll to footer section and see twitter old logo

Expected behavior
Twitter logo should be changed to X

Screenshot

<img width="960" alt="Screenshot 2023-09-10 200611" src="https://github.com/NangoHQ/nango/assets/91591901/c15c1f39-fef8-4613-a233-ecc9ebe424f1">

@mdp 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by khaliqgant** [comment] 2023-10-17 17:46
Dupe of #976

**Closed as completed by khaliqgant** 2023-10-17 17:46 UTC
Labels: enhancement
